In [22]:
import numpy as np
import h5py
import bdpy

In [23]:
hdf_path = '../../../ImageFeatures.h5'
data_feature = bdpy.BData(hdf_path)


In [59]:
y = data_feature.select('cnn8')             # Image features
y_label = data_feature.select('ImageID')  # Image labels
y_catlabels = data_feature.select('CatID') 
# datatype = data_feature.select('DataType')

In [60]:
y_catlabels.shape

(16622, 1)

In [61]:
cat_set = np.unique(y_catlabels)

In [62]:
cat_set.shape

(15522,)

In [63]:
cat_set

array([7.8460000e+03, 2.1265000e+04, 1.4166900e+05, ..., 1.5093049e+07,
       1.5093137e+07, 1.5093298e+07])

In [64]:
y.shape

(16622, 1000)

In [65]:
print(y_label[~np.isnan(y_label)].shape)
dataset_ids = np.where(~np.isnan(y_label))[0]
y_catlabels = y_catlabels[dataset_ids]


(1250,)


In [66]:
y_catlabels.shape

(1250, 1)

In [69]:
print(y_catlabels[:20])
print(y_catlabels[1190:1240])
print(y_catlabels[1201] in y_catlabels[:1200])

[[1518878.]
 [1518878.]
 [1518878.]
 [1518878.]
 [1518878.]
 [1518878.]
 [1518878.]
 [1518878.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1639765.]
 [1645776.]
 [1645776.]
 [1645776.]
 [1645776.]]
[[12596148.]
 [12596148.]
 [13111881.]
 [13111881.]
 [13111881.]
 [13111881.]
 [13111881.]
 [13111881.]
 [13111881.]
 [13111881.]
 [ 1443537.]
 [ 1621127.]
 [ 1677366.]
 [ 1846331.]
 [ 1858441.]
 [ 1943899.]
 [ 1976957.]
 [ 2071294.]
 [ 2128385.]
 [ 2139199.]
 [ 2190790.]
 [ 2274259.]
 [ 2416519.]
 [ 2437136.]
 [ 2437971.]
 [ 2690373.]
 [ 2797295.]
 [ 2824058.]
 [ 2882301.]
 [ 2916179.]
 [ 2950256.]
 [ 2951358.]
 [ 3064758.]
 [ 3122295.]
 [ 3124170.]
 [ 3237416.]
 [ 3272010.]
 [ 3345837.]
 [ 3379051.]
 [ 3452741.]
 [ 3455488.]
 [ 3482252.]
 [ 3495258.]
 [ 3584254.]
 [ 3626115.]
 [ 3710193.]
 [ 3716966.]
 [ 3761084.]
 [ 3767745.]
 [ 3941684.]]
False


In [5]:
file.keys()

<KeysViewHDF5 ['callStack', 'callStackCode', 'createDate', 'createDateRaw', 'createScript', 'dataSet', 'metaData']>

In [7]:
dataSet = file['dataSet']

In [9]:
print(dir(dataSet))
print(dataSet.shape)

['__array__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cache_props', '_d', '_dcpl', '_dxpl', '_e', '_extent_type', '_fast_read_ok', '_fast_reader', '_filters', '_id', '_is_empty', '_lapl', '_lcpl', '_local', '_readonly', '_selector', 'asstr', 'astype', 'attrs', 'chunks', 'compression', 'compression_opts', 'dims', 'dtype', 'external', 'fields', 'file', 'fillvalue', 'fletcher32', 'flush', 'id', 'is_virtual', 'iter_chunks', 'len', 'make_scale', 'maxshape', 'name', 'nbytes', 'ndim', 'parent', 'read_direct', 'ref', 'refresh', 'regionref', 'resize', 'scaleoffset', 'shape', 'shuffl

In [10]:
dataSet.file

<HDF5 file "ImageFeatures.h5" (mode r)>

In [14]:
dataSet.name

'/dataSet'

In [15]:
file

<HDF5 file "ImageFeatures.h5" (mode r)>

In [18]:
DateRaw = file['createDateRaw']
DateRaw

<HDF5 dataset "createDateRaw": shape (), type "<f8">

In [20]:
DateRaw.shape

()